#ifndef _CONFIG_
#define _CONFIG_
#define ULTRASOUND_SENSOR_BACK_THRESHOLD 70
#define ULTRASOUND_SENSOR_FRONT_THRESHOLD 100
#define DEBUG true
#define SPEED_TRANSLATION 70
#define SPEED_ROTATION 120
#endif /* _CONFIG_ */
