#ifndef _CONFIG_
#define _CONFIG_

#define ULTRASOUND_SENSOR_BACK_THRESHOLD 70
#define ULTRASOUND_SENSOR_FRONT_THRESHOLD 70
#define DEBUG true
#define SPEED_TRANSLATION 100
#define SPEED_ROTATION 150

#endif /* _CONFIG_ */