#ifndef _CONFIG_
#define _CONFIG_
#define ULTRASOUND_SENSOR_BACK_THRESHOLD 70
#define ULTRASOUND_SENSOR_FRONT_THRESHOLD 80
#define DEBUG true
#define SPEED_TRANSLATION 250
#define SPEED_ROTATION 250
#endif /* _CONFIG_ */
